model_name: detr
data:
  train_annotation_path: /home/huffman/data/annotations/instances_train2017.json
#  train_annotation_path: /home/huffman/data/annotations/instances_val2017.json
  val_annotation_path: /home/huffman/data/annotations/instances_val2017.json
  train_img_root: /home/huffman/data/train2017
#  train_img_root: /home/huffman/data/val2017
  val_img_root: /home/huffman/data/val2017
  min_thresh: 640
  max_thresh: 1024
  batch_size: 4
  num_workers: 4
  debug: False
  remove_blank: True
  use_crowd: False

model:
  num_cls: 80
  backbone: resnet50

optim:
  backbone_lr: 0.00002
  lr: 0.0002
  weight_decay: 0.0001
  epochs: 300
  decay_steps: 200

val:
  interval: 1
  weight_path: weights
gpus: 0,1,2,3,4,5,6,7